version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=production
    networks:
      - chatapp-net

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL=http://backend:5001
    depends_on:
      - backend
    networks:
      - chatapp-net

networks:
  chatapp-net:
    driver: bridge
